USE nyc_taxi_ldw;

CREATE EXTERNAL FILE FORMAT csv_file_format
WITH
(
    FORMAT_TYPE=DELIMITEDTEXT,
    FORMAT_OPTIONS (
        FIELD_TERMINATOR = ','
        , STRING_DELIMITER = '"'
        , FIRST_ROW = 2 -- ONLY AVAILABLE FOR AZURE SYNAPSE ANALYTICS
        , USE_TYPE_DEFAULT = FALSE
        , ENCODING ='UTF8'
        , PARSER_VERSION = '2.0'
    )
);